# whether lambda function could raise Exception
# Yes, for this test case

f0 = lambda : return False
f1 = lambda: return FFalse

print f0()
print f1()
